export const REGISTER_WITH_EMAIL_PASSWORD = "REGISTER_WITH_EMAIL_PASSWORD";
export const SIGN_IN_WITH_EMAIL_PASSWORD = "SIGN_IN_WITH_EMAIL_PASSWORD";
export const SIGN_IN_WITH_GOOGLE = "SIGN_UP_WITH_GOOGLE";
export const SIGN_IN_WITH_FACEBOOK = "SIGN_UP_WITH_FACEBOOK";
export const SIGN_OUT = "SIGN_OUT";
